# Generated by Django 3.1.7 on 2021-04-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(blank=True, choices=[('In progress', 'In progress'), ('Finished', 'Finished')], max_length=50, null=True),
        ),
    ]
